python get_map_neurons.py  \
    --in_kaggle \
    --dataset_kaggle "inayarahmanisa/activationxx-gemma9-flores"\
    --filename "act_flores200_997_False.pt" \
    --num_layer 42 \
    --model_name_inf "gemma9" \
    --dataset_name_inf "flores" \
    --kaggle_dataname_to_save "lsnxx-gemma9-flores" \
    --threshold 0.99 0.95 0.90 0.3 \
    --top_k 897 \
    --is_update
