python get_map_neurons.py  \
    --in_kaggle \
    --dataset_kaggle "inayarahmanisa/activationxx-qwen7-neurons"\
    --filename "act_flores200_997_False.pt" \
    --num_layer 28 \
    --model_name_inf "qwen7" \
    --dataset_name_inf "flores" \
    --kaggle_dataname_to_save "lsnxx-qwen7-flores" \
    --threshold 0.99 0.95 0.90 0.3 \
    --top_bottom_k 1000 \
    --is_update