python get_map_neurons.py  \
    --in_kaggle \
    --dataset_kaggle "inayarahmanisa/activationxx-sea7-flores"\
    --filename "act_flores200_997_False.pt" \
    --num_layer 28 \
    --model_name_inf "sea7" \
    --dataset_name_inf "flores" \
    --kaggle_dataname_to_save "lsnxx-sea7-flores" \
    --threshold 0.99 0.95 0.90 0.3 \
    --top_bottom_k 1426 \
    --is_update