python intervention_tasks_gemma.py \
    --dataset_kaggle "inayarahmanisa/lsnxx-qwen7-flores" \
    --lsn_filename "qwen7_flores" \
    --ld_filename "lang_dict" \
    --dataset_kaggle_replacer "inayarahmanisa/activationxx-qwen7-flores" \
    --replacer_filename "max.pt" \
    --hf_token "***REMOVED***" \
    --model_name "Qwen/Qwen2.5-7B-Instruct" \
    --dataset_name "Muennighoff/flores200"  \
    --split devtest \
    --noncross \
    --replace_method fixed \
    --operation_non_target ".1" \
    --operation_target "=10" \
    --metrics "bleu" \
    --kaggle_dataname_to_save "bleu-flores2-prompted" \
    --parent_dir_to_save "" \
    --selected_langs "eng_Latn-nld_Latn" "eng_Latn-ind_Latn" "eng_Latn-zsm_Latn" "eng_Latn-vie_Latn" "eng_Latn-jpn_Jpan" "eng_Latn-zho_Hans" "eng_Latn-fra_Latn" "eng_Latn-por_Latn" "eng_Latn-rus_Cyrl" "eng_Latn-est_Latn" "eng_Latn-hat_Latn" "eng_Latn-ita_Latn" "eng_Latn-quy_Latn" "eng_Latn-swh_Latn" "eng_Latn-tam_Taml" "eng_Latn-tha_Thai" "eng_Latn-tur_Latn" \
    --target_langs 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 \
    --is_update \
    --batch_size 10 \
    > qwen_bleu_lape.txt 2>&1